# Generated by Django 4.0 on 2023-04-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_product_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDimension',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dimension_image', models.ImageField(null=True, upload_to='product_diamension_images')),
                ('size_chart', models.JSONField()),
            ],
            options={
                'db_table': 'product_dimension',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='dimension_type',
            field=models.CharField(blank=True, choices=[('centimeters', 'centimeters'), ('inches', 'inches')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prouduct_identifier_type',
            field=models.CharField(blank=True, choices=[('ASIN', 'ASIN'), ('EAN', 'EAN'), ('GCID', 'GCID'), ('ISBN', 'ISBN'), ('UPC', 'UPC')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('Oz', 'Oz'), ('kilograms', 'kilograms'), ('pounds', 'pounds')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.productdimension'),
        ),
    ]
