# Generated by Django 4.0 on 2023-04-10 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_productdimension_alter_product_dimension_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimension_type',
            field=models.CharField(blank=True, choices=[('inches', 'inches'), ('centimeters', 'centimeters')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_chart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='account.productdimension'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('pounds', 'pounds'), ('kilograms', 'kilograms'), ('Oz', 'Oz')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('review', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='account.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='account.user')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
