# Generated by Django 4.0 on 2023-04-10 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_product_prouduct_identifier_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prouduct_identifier_type',
            field=models.CharField(blank=True, choices=[('GCID', 'GCID'), ('ISBN', 'ISBN'), ('ASIN', 'ASIN'), ('UPC', 'UPC'), ('EAN', 'EAN')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='account.productdimension'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kilograms', 'kilograms'), ('pounds', 'pounds'), ('Oz', 'Oz')], max_length=255, null=True),
        ),
    ]
