# Generated by Django 4.0 on 2023-04-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_cart_quantity_alter_product_dimension_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimension_type',
            field=models.CharField(blank=True, choices=[('inches', 'inches'), ('centimeters', 'centimeters')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prouduct_identifier_type',
            field=models.CharField(blank=True, choices=[('GCID', 'GCID'), ('UPC', 'UPC'), ('EAN', 'EAN'), ('ISBN', 'ISBN'), ('ASIN', 'ASIN')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('Oz', 'Oz'), ('pounds', 'pounds'), ('kilograms', 'kilograms')], max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('product', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='Favourite',
            unique_together={('product', 'user')},
        ),
    ]
