# Generated by Django 4.0 on 2023-04-12 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_product_prouduct_identifier_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'new'), ('used', 'used')], default='new', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='prouduct_identifier_type',
            field=models.CharField(blank=True, choices=[('GCID', 'GCID'), ('EAN', 'EAN'), ('ISBN', 'ISBN'), ('ASIN', 'ASIN'), ('UPC', 'UPC')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('pounds', 'pounds'), ('kilograms', 'kilograms'), ('Oz', 'Oz')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=255)),
                ('address_line1', models.TextField()),
                ('address_line2', models.TextField()),
                ('labdmark', models.TextField(blank=True, null=True)),
                ('town', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='account.user')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
