# Generated by Django 4.0 on 2023-04-12 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_cart_total_alter_product_dimension_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'new'), ('used', 'used')], default='new', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='prouduct_identifier_type',
            field=models.CharField(blank=True, choices=[('EAN', 'EAN'), ('UPC', 'UPC'), ('GCID', 'GCID'), ('ISBN', 'ISBN'), ('ASIN', 'ASIN')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('Oz', 'Oz'), ('pounds', 'pounds'), ('kilograms', 'kilograms')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_payment_status', models.CharField(default='pending', max_length=20)),
                ('order_payment_id', models.CharField(max_length=255)),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_orders', to='account.address')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.cart')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_orders', to='account.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.user')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
