# Generated by Django 3.2 on 2023-04-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_product_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(related_name='orders', to='account.Cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('used', 'used'), ('new', 'new')], default='new', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimension_type',
            field=models.CharField(blank=True, choices=[('inches', 'inches'), ('centimeters', 'centimeters')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prouduct_identifier_type',
            field=models.CharField(blank=True, choices=[('ASIN', 'ASIN'), ('EAN', 'EAN'), ('UPC', 'UPC'), ('ISBN', 'ISBN'), ('GCID', 'GCID')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kilograms', 'kilograms'), ('pounds', 'pounds'), ('Oz', 'Oz')], max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
    ]
