# Generated by Django 4.0 on 2023-04-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20230413_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, choices=[(' SLL', ' SLL'), (' KES', ' KES'), (' TWD', ' TWD'), (' GHS', ' GHS'), (' PAB', ' PAB'), (' MNT', ' MNT'), (' DZD', ' DZD'), (' HUF', ' HUF'), (' MGA', ' MGA'), (' PHP', ' PHP'), (' UZS', ' UZS'), (' RSD', ' RSD'), (' EUR', ' EUR'), (' GNF', ' GNF'), (' BAM', ' BAM'), (' ETB', ' ETB'), (' GIP', ' GIP'), (' HNL', ' HNL'), (' GTQ', ' GTQ'), (' BDT', ' BDT'), (' MYR', ' MYR'), (' TZS', ' TZS'), (' AFN', ' AFN'), (' AOA', ' AOA'), (' CNY', ' CNY'), (' FJD', ' FJD'), (' HRK', ' HRK'), (' NOK', ' NOK'), (' BZD', ' BZD'), (' MOP', ' MOP'), (' CHF', ' CHF'), (' GBP', ' GBP'), (' MRO', ' MRO'), (' BYN', ' BYN'), (' ILS', ' ILS'), (' SCR', ' SCR'), (' EEK', ' EEK'), (' QAR', ' QAR'), (' JPY', ' JPY'), (' MVR', ' MVR'), (' LRD', ' LRD'), (' VND', ' VND'), (' RUB', ' RUB'), (' KZT', ' KZT'), (' UYU', ' UYU'), (' FKP', ' FKP'), (' SOS', ' SOS'), (' MMK', ' MMK'), (' EGP', ' EGP'), (' SHP', ' SHP'), (' BOB', ' BOB'), (' XOF', ' XOF'), (' XAF', ' XAF'), (' TRY', ' TRY'), (' TTD', ' TTD'), (' DKK', ' DKK'), (' MZN', ' MZN'), (' NPR', ' NPR'), (' UAH', ' UAH'), (' ANG', ' ANG'), (' SZL', ' SZL'), (' HTG', ' HTG'), (' THB', ' THB'), (' LAK', ' LAK'), (' OMR', ' OMR'), (' LVL', ' LVL'), (' MAD', ' MAD'), (' ALL', ' ALL'), (' NIO', ' NIO'), (' INR', ' INR'), (' AED', ' AED'), (' KWD', ' KWD'), (' HKD', ' HKD'), (' AMD', ' AMD'), (' BMD', ' BMD'), (' CLP', ' CLP'), (' CZK', ' CZK'), (' BIF', ' BIF'), (' GYD', ' GYD'), (' PEN', ' PEN'), (' AZN', ' AZN'), (' PGK', ' PGK'), (' MKD', ' MKD'), (' BBD', ' BBD'), (' RWF', ' RWF'), (' TJS', ' TJS'), (' KRW', ' KRW'), (' KGS', ' KGS'), (' PLN', ' PLN'), (' GEL', ' GEL'), (' STD', ' STD'), (' DOP', ' DOP'), (' NZD', ' NZD'), (' KYD', ' KYD'), (' SGD', ' SGD'), (' XCD', ' XCD'), (' NAD', ' NAD'), (' SRD', ' SRD'), (' TND', ' TND'), (' BWP', ' BWP'), (' RON', ' RON'), (' MDL', ' MDL'), (' JOD', ' JOD'), (' ISK', ' ISK'), (' PYG', ' PYG'), (' XPF', ' XPF'), (' YER', ' YER'), (' KMF', ' KMF'), (' VUV', ' VUV'), (' JMD', ' JMD'), (' ZMW', ' ZMW'), (' VEF', ' VEF'), (' COP', ' COP'), (' BRL', ' BRL'), (' USDC', ' USDC'), (' CAD', ' CAD'), (' MUR', ' MUR'), (' SBD', ' SBD'), (' BSD', ' BSD'), (' ARS', ' ARS'), (' SEK', ' SEK'), (' LKR', ' LKR'), (' CDF', ' CDF'), (' DJF', ' DJF'), (' BND', ' BND'), (' PKR', ' PKR'), (' SVC', ' SVC'), (' UGX', ' UGX'), (' AWG', ' AWG'), (' BHD', ' BHD'), (' TOP', ' TOP'), (' AUD', ' AUD'), (' SLE', ' SLE'), (' GMD', ' GMD'), (' LSL', ' LSL'), (' WST', ' WST'), (' LBP', ' LBP'), (' BTN', ' BTN'), (' NGN', ' NGN'), (' IDR', ' IDR'), (' LTL', ' LTL'), (' CVE', ' CVE'), (' KHR', ' KHR'), (' BGN', ' BGN'), (' MXN', ' MXN'), (' MWK', ' MWK'), ('USD', 'USD'), (' CRC', ' CRC'), (' SAR', ' SAR'), (' ZAR', ' ZAR')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prouduct_identifier_type',
            field=models.CharField(blank=True, choices=[('ASIN', 'ASIN'), ('ISBN', 'ISBN'), ('EAN', 'EAN'), ('UPC', 'UPC'), ('GCID', 'GCID')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kilograms', 'kilograms'), ('Oz', 'Oz'), ('pounds', 'pounds')], max_length=255, null=True),
        ),
    ]
