# Generated by Django 4.0 on 2023-04-20 10:25

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_order_currency_alter_product_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordInvite',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(blank=True, default=account.models.generate_unique_code, max_length=8, null=True)),
            ],
            options={
                'db_table': 'forgot_password_invite',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, choices=[('PLN', 'PLN'), ('BOB', 'BOB'), ('TRY', 'TRY'), ('MZN', 'MZN'), ('KGS', 'KGS'), ('LAK', 'LAK'), ('TJS', 'TJS'), ('CAD', 'CAD'), ('BIF', 'BIF'), ('RWF', 'RWF'), ('DZD', 'DZD'), ('SCR', 'SCR'), ('EEK', 'EEK'), ('MNT', 'MNT'), ('HUF', 'HUF'), ('LKR', 'LKR'), ('VUV', 'VUV'), ('MRO', 'MRO'), ('CVE', 'CVE'), ('SOS', 'SOS'), ('DKK', 'DKK'), ('FKP', 'FKP'), ('USDC', 'USDC'), ('HTG', 'HTG'), ('LTL', 'LTL'), ('CZK', 'CZK'), ('XCD', 'XCD'), ('NPR', 'NPR'), ('NGN', 'NGN'), ('JPY', 'JPY'), ('RSD', 'RSD'), ('MYR', 'MYR'), ('DJF', 'DJF'), ('MUR', 'MUR'), ('UGX', 'UGX'), ('ISK', 'ISK'), ('KWD', 'KWD'), ('QAR', 'QAR'), ('USD', 'USD'), ('MKD', 'MKD'), ('BGN', 'BGN'), ('SAR', 'SAR'), ('THB', 'THB'), ('ETB', 'ETB'), ('EUR', 'EUR'), ('SLE', 'SLE'), ('EGP', 'EGP'), ('KHR', 'KHR'), ('PAB', 'PAB'), ('JMD', 'JMD'), ('COP', 'COP'), ('PYG', 'PYG'), ('CDF', 'CDF'), ('KRW', 'KRW'), ('PEN', 'PEN'), ('AED', 'AED'), ('SZL', 'SZL'), ('RUB', 'RUB'), ('AOA', 'AOA'), ('AWG', 'AWG'), ('BAM', 'BAM'), ('UZS', 'UZS'), ('XPF', 'XPF'), ('GMD', 'GMD'), ('MGA', 'MGA'), ('MAD', 'MAD'), ('GTQ', 'GTQ'), ('GNF', 'GNF'), ('SHP', 'SHP'), ('TOP', 'TOP'), ('STD', 'STD'), ('MWK', 'MWK'), ('BWP', 'BWP'), ('INR', 'INR'), ('XAF', 'XAF'), ('WST', 'WST'), ('BDT', 'BDT'), ('BBD', 'BBD'), ('AUD', 'AUD'), ('NIO', 'NIO'), ('NAD', 'NAD'), ('BTN', 'BTN'), ('NZD', 'NZD'), ('SVC', 'SVC'), ('HKD', 'HKD'), ('VND', 'VND'), ('CLP', 'CLP'), ('CNY', 'CNY'), ('UAH', 'UAH'), ('LBP', 'LBP'), ('SEK', 'SEK'), ('MOP', 'MOP'), ('XOF', 'XOF'), ('ILS', 'ILS'), ('GHS', 'GHS'), ('KES', 'KES'), ('JOD', 'JOD'), ('GBP', 'GBP'), ('SGD', 'SGD'), ('KZT', 'KZT'), ('DOP', 'DOP'), ('BRL', 'BRL'), ('BZD', 'BZD'), ('MVR', 'MVR'), ('SRD', 'SRD'), ('MMK', 'MMK'), ('UYU', 'UYU'), ('GYD', 'GYD'), ('BYN', 'BYN'), ('SLL', 'SLL'), ('CHF', 'CHF'), ('HNL', 'HNL'), ('PHP', 'PHP'), ('AZN', 'AZN'), ('ARS', 'ARS'), ('VEF', 'VEF'), ('YER', 'YER'), ('HRK', 'HRK'), ('LSL', 'LSL'), ('TWD', 'TWD'), ('ANG', 'ANG'), ('BND', 'BND'), ('BMD', 'BMD'), ('KYD', 'KYD'), ('BHD', 'BHD'), ('AFN', 'AFN'), ('MXN', 'MXN'), ('NOK', 'NOK'), ('TND', 'TND'), ('KMF', 'KMF'), ('IDR', 'IDR'), ('MDL', 'MDL'), ('SBD', 'SBD'), ('GEL', 'GEL'), ('LVL', 'LVL'), ('CRC', 'CRC'), ('PGK', 'PGK'), ('OMR', 'OMR'), ('ZAR', 'ZAR'), ('FJD', 'FJD'), ('AMD', 'AMD'), ('TZS', 'TZS'), ('LRD', 'LRD'), ('ALL', 'ALL'), ('TTD', 'TTD'), ('ZMW', 'ZMW'), ('BSD', 'BSD'), ('RON', 'RON'), ('PKR', 'PKR'), ('GIP', 'GIP')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('used', 'used'), ('new', 'new')], default='new', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='prouduct_identifier_type',
            field=models.CharField(blank=True, choices=[('UPC', 'UPC'), ('ASIN', 'ASIN'), ('EAN', 'EAN'), ('GCID', 'GCID'), ('ISBN', 'ISBN')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kilograms', 'kilograms'), ('Oz', 'Oz'), ('pounds', 'pounds')], max_length=255, null=True),
        ),
    ]
