# Generated by Django 4.0 on 2023-04-21 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_forgotpasswordinvite_alter_order_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribe_to_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, choices=[('KYD', 'KYD'), ('SCR', 'SCR'), ('GBP', 'GBP'), ('FJD', 'FJD'), ('PYG', 'PYG'), ('BBD', 'BBD'), ('ETB', 'ETB'), ('NAD', 'NAD'), ('KMF', 'KMF'), ('XCD', 'XCD'), ('BND', 'BND'), ('HNL', 'HNL'), ('WST', 'WST'), ('KZT', 'KZT'), ('SOS', 'SOS'), ('SRD', 'SRD'), ('BRL', 'BRL'), ('MWK', 'MWK'), ('AWG', 'AWG'), ('NGN', 'NGN'), ('XAF', 'XAF'), ('NOK', 'NOK'), ('PAB', 'PAB'), ('NIO', 'NIO'), ('AOA', 'AOA'), ('NZD', 'NZD'), ('CHF', 'CHF'), ('COP', 'COP'), ('LKR', 'LKR'), ('TWD', 'TWD'), ('RSD', 'RSD'), ('NPR', 'NPR'), ('CLP', 'CLP'), ('ZAR', 'ZAR'), ('HRK', 'HRK'), ('GYD', 'GYD'), ('MKD', 'MKD'), ('LRD', 'LRD'), ('EEK', 'EEK'), ('SVC', 'SVC'), ('VUV', 'VUV'), ('TTD', 'TTD'), ('BSD', 'BSD'), ('HKD', 'HKD'), ('ILS', 'ILS'), ('BDT', 'BDT'), ('SLE', 'SLE'), ('VEF', 'VEF'), ('DOP', 'DOP'), ('GTQ', 'GTQ'), ('BMD', 'BMD'), ('RWF', 'RWF'), ('GNF', 'GNF'), ('GIP', 'GIP'), ('OMR', 'OMR'), ('BIF', 'BIF'), ('AED', 'AED'), ('MMK', 'MMK'), ('LBP', 'LBP'), ('KWD', 'KWD'), ('BGN', 'BGN'), ('IDR', 'IDR'), ('MOP', 'MOP'), ('ZMW', 'ZMW'), ('BOB', 'BOB'), ('BHD', 'BHD'), ('PHP', 'PHP'), ('MVR', 'MVR'), ('TJS', 'TJS'), ('AFN', 'AFN'), ('CAD', 'CAD'), ('UZS', 'UZS'), ('HTG', 'HTG'), ('TRY', 'TRY'), ('STD', 'STD'), ('TOP', 'TOP'), ('ISK', 'ISK'), ('CZK', 'CZK'), ('GMD', 'GMD'), ('AUD', 'AUD'), ('JMD', 'JMD'), ('BAM', 'BAM'), ('SGD', 'SGD'), ('FKP', 'FKP'), ('SEK', 'SEK'), ('AMD', 'AMD'), ('USDC', 'USDC'), ('MNT', 'MNT'), ('SAR', 'SAR'), ('EUR', 'EUR'), ('LVL', 'LVL'), ('JOD', 'JOD'), ('SHP', 'SHP'), ('ALL', 'ALL'), ('HUF', 'HUF'), ('TND', 'TND'), ('PLN', 'PLN'), ('LSL', 'LSL'), ('SLL', 'SLL'), ('RUB', 'RUB'), ('DJF', 'DJF'), ('LTL', 'LTL'), ('MAD', 'MAD'), ('DZD', 'DZD'), ('MZN', 'MZN'), ('RON', 'RON'), ('MXN', 'MXN'), ('BWP', 'BWP'), ('LAK', 'LAK'), ('VND', 'VND'), ('XPF', 'XPF'), ('UAH', 'UAH'), ('KGS', 'KGS'), ('PKR', 'PKR'), ('QAR', 'QAR'), ('YER', 'YER'), ('DKK', 'DKK'), ('MRO', 'MRO'), ('EGP', 'EGP'), ('GHS', 'GHS'), ('UGX', 'UGX'), ('AZN', 'AZN'), ('CRC', 'CRC'), ('KRW', 'KRW'), ('MDL', 'MDL'), ('BTN', 'BTN'), ('SZL', 'SZL'), ('INR', 'INR'), ('BZD', 'BZD'), ('ANG', 'ANG'), ('ARS', 'ARS'), ('KHR', 'KHR'), ('BYN', 'BYN'), ('CVE', 'CVE'), ('JPY', 'JPY'), ('PGK', 'PGK'), ('MGA', 'MGA'), ('SBD', 'SBD'), ('USD', 'USD'), ('PEN', 'PEN'), ('MUR', 'MUR'), ('GEL', 'GEL'), ('CDF', 'CDF'), ('TZS', 'TZS'), ('THB', 'THB'), ('XOF', 'XOF'), ('UYU', 'UYU'), ('KES', 'KES'), ('CNY', 'CNY'), ('MYR', 'MYR')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimension_type',
            field=models.CharField(blank=True, choices=[('centimeters', 'centimeters'), ('inches', 'inches')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prouduct_identifier_type',
            field=models.CharField(blank=True, choices=[('GCID', 'GCID'), ('EAN', 'EAN'), ('ASIN', 'ASIN'), ('ISBN', 'ISBN'), ('UPC', 'UPC')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_alerts', to='account.user')),
                ('user', models.ManyToManyField(related_name='alert_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
    ]
