# Generated by Django 4.0 on 2023-04-21 10:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_user_is_subscribe_to_news_alter_order_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('valid_from', models.DateTimeField(null=True)),
                ('valid_to', models.DateTimeField(null=True)),
                ('discount_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_type', models.CharField(choices=[('percentage', 'percentage'), ('currency', 'currency')], max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('one_time_only', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='account.user')),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, choices=[('BYN', 'BYN'), ('INR', 'INR'), ('KMF', 'KMF'), ('DKK', 'DKK'), ('SAR', 'SAR'), ('SCR', 'SCR'), ('USDC', 'USDC'), ('FKP', 'FKP'), ('XAF', 'XAF'), ('NAD', 'NAD'), ('SZL', 'SZL'), ('TZS', 'TZS'), ('GBP', 'GBP'), ('MUR', 'MUR'), ('ILS', 'ILS'), ('GHS', 'GHS'), ('TTD', 'TTD'), ('SRD', 'SRD'), ('BMD', 'BMD'), ('AFN', 'AFN'), ('DZD', 'DZD'), ('BOB', 'BOB'), ('COP', 'COP'), ('TWD', 'TWD'), ('UAH', 'UAH'), ('SEK', 'SEK'), ('THB', 'THB'), ('PYG', 'PYG'), ('USD', 'USD'), ('GYD', 'GYD'), ('TOP', 'TOP'), ('KHR', 'KHR'), ('SLL', 'SLL'), ('XPF', 'XPF'), ('XOF', 'XOF'), ('UYU', 'UYU'), ('BDT', 'BDT'), ('AUD', 'AUD'), ('RWF', 'RWF'), ('MOP', 'MOP'), ('AOA', 'AOA'), ('ZMW', 'ZMW'), ('EUR', 'EUR'), ('MAD', 'MAD'), ('LAK', 'LAK'), ('MGA', 'MGA'), ('LTL', 'LTL'), ('GNF', 'GNF'), ('MMK', 'MMK'), ('CVE', 'CVE'), ('PGK', 'PGK'), ('BRL', 'BRL'), ('DJF', 'DJF'), ('BSD', 'BSD'), ('YER', 'YER'), ('ANG', 'ANG'), ('LSL', 'LSL'), ('KES', 'KES'), ('MNT', 'MNT'), ('AWG', 'AWG'), ('CHF', 'CHF'), ('CRC', 'CRC'), ('BGN', 'BGN'), ('NGN', 'NGN'), ('TRY', 'TRY'), ('QAR', 'QAR'), ('PHP', 'PHP'), ('BND', 'BND'), ('TND', 'TND'), ('NIO', 'NIO'), ('HUF', 'HUF'), ('SGD', 'SGD'), ('DOP', 'DOP'), ('CZK', 'CZK'), ('KGS', 'KGS'), ('UGX', 'UGX'), ('HTG', 'HTG'), ('VND', 'VND'), ('LKR', 'LKR'), ('ZAR', 'ZAR'), ('GEL', 'GEL'), ('ARS', 'ARS'), ('LBP', 'LBP'), ('MVR', 'MVR'), ('SHP', 'SHP'), ('BTN', 'BTN'), ('CNY', 'CNY'), ('XCD', 'XCD'), ('BBD', 'BBD'), ('KRW', 'KRW'), ('PKR', 'PKR'), ('AMD', 'AMD'), ('OMR', 'OMR'), ('BIF', 'BIF'), ('LRD', 'LRD'), ('RSD', 'RSD'), ('KZT', 'KZT'), ('ALL', 'ALL'), ('JMD', 'JMD'), ('HRK', 'HRK'), ('NPR', 'NPR'), ('MDL', 'MDL'), ('NZD', 'NZD'), ('ETB', 'ETB'), ('GIP', 'GIP'), ('EGP', 'EGP'), ('JOD', 'JOD'), ('GTQ', 'GTQ'), ('TJS', 'TJS'), ('RUB', 'RUB'), ('MZN', 'MZN'), ('ISK', 'ISK'), ('GMD', 'GMD'), ('PLN', 'PLN'), ('VEF', 'VEF'), ('PAB', 'PAB'), ('KYD', 'KYD'), ('SLE', 'SLE'), ('MXN', 'MXN'), ('AZN', 'AZN'), ('PEN', 'PEN'), ('SBD', 'SBD'), ('NOK', 'NOK'), ('SOS', 'SOS'), ('IDR', 'IDR'), ('RON', 'RON'), ('KWD', 'KWD'), ('HKD', 'HKD'), ('BZD', 'BZD'), ('BHD', 'BHD'), ('HNL', 'HNL'), ('MWK', 'MWK'), ('EEK', 'EEK'), ('LVL', 'LVL'), ('MKD', 'MKD'), ('MRO', 'MRO'), ('VUV', 'VUV'), ('JPY', 'JPY'), ('CDF', 'CDF'), ('UZS', 'UZS'), ('MYR', 'MYR'), ('SVC', 'SVC'), ('CAD', 'CAD'), ('STD', 'STD'), ('AED', 'AED'), ('BWP', 'BWP'), ('BAM', 'BAM'), ('WST', 'WST'), ('FJD', 'FJD'), ('CLP', 'CLP')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'new'), ('used', 'used')], default='new', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimension_type',
            field=models.CharField(blank=True, choices=[('inches', 'inches'), ('centimeters', 'centimeters')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prouduct_identifier_type',
            field=models.CharField(blank=True, choices=[('UPC', 'UPC'), ('GCID', 'GCID'), ('ASIN', 'ASIN'), ('EAN', 'EAN'), ('ISBN', 'ISBN')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('Oz', 'Oz'), ('kilograms', 'kilograms'), ('pounds', 'pounds')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CouponUser',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'db_table': 'coupon_user',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ManyToManyField(related_name='coupons_user', through='account.CouponUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
