# Generated by Django 4.0 on 2023-04-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_coupon_alter_order_currency_alter_product_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('currency', 'currency'), ('percentage', 'percentage')], max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, choices=[('SLE', 'SLE'), ('CVE', 'CVE'), ('DZD', 'DZD'), ('LBP', 'LBP'), ('BOB', 'BOB'), ('HRK', 'HRK'), ('BHD', 'BHD'), ('CHF', 'CHF'), ('KES', 'KES'), ('LTL', 'LTL'), ('ETB', 'ETB'), ('STD', 'STD'), ('BRL', 'BRL'), ('KRW', 'KRW'), ('JPY', 'JPY'), ('GYD', 'GYD'), ('EEK', 'EEK'), ('USD', 'USD'), ('RSD', 'RSD'), ('EUR', 'EUR'), ('MZN', 'MZN'), ('PLN', 'PLN'), ('SCR', 'SCR'), ('PKR', 'PKR'), ('AED', 'AED'), ('NZD', 'NZD'), ('INR', 'INR'), ('ZMW', 'ZMW'), ('MNT', 'MNT'), ('BYN', 'BYN'), ('MRO', 'MRO'), ('HNL', 'HNL'), ('AFN', 'AFN'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('SRD', 'SRD'), ('GMD', 'GMD'), ('DOP', 'DOP'), ('ALL', 'ALL'), ('BWP', 'BWP'), ('VUV', 'VUV'), ('PAB', 'PAB'), ('ANG', 'ANG'), ('BSD', 'BSD'), ('HKD', 'HKD'), ('MKD', 'MKD'), ('MOP', 'MOP'), ('AMD', 'AMD'), ('LRD', 'LRD'), ('JMD', 'JMD'), ('BGN', 'BGN'), ('RWF', 'RWF'), ('TOP', 'TOP'), ('SZL', 'SZL'), ('SLL', 'SLL'), ('KMF', 'KMF'), ('MVR', 'MVR'), ('EGP', 'EGP'), ('DJF', 'DJF'), ('QAR', 'QAR'), ('UGX', 'UGX'), ('NPR', 'NPR'), ('HTG', 'HTG'), ('LVL', 'LVL'), ('MUR', 'MUR'), ('SHP', 'SHP'), ('XPF', 'XPF'), ('KZT', 'KZT'), ('KWD', 'KWD'), ('XAF', 'XAF'), ('YER', 'YER'), ('MDL', 'MDL'), ('FJD', 'FJD'), ('MAD', 'MAD'), ('BDT', 'BDT'), ('ARS', 'ARS'), ('TRY', 'TRY'), ('CDF', 'CDF'), ('BZD', 'BZD'), ('MYR', 'MYR'), ('SVC', 'SVC'), ('LAK', 'LAK'), ('GIP', 'GIP'), ('AZN', 'AZN'), ('KGS', 'KGS'), ('BAM', 'BAM'), ('BMD', 'BMD'), ('MWK', 'MWK'), ('COP', 'COP'), ('MXN', 'MXN'), ('NGN', 'NGN'), ('RUB', 'RUB'), ('BTN', 'BTN'), ('ISK', 'ISK'), ('XCD', 'XCD'), ('UYU', 'UYU'), ('THB', 'THB'), ('CLP', 'CLP'), ('TND', 'TND'), ('JOD', 'JOD'), ('GHS', 'GHS'), ('PGK', 'PGK'), ('CZK', 'CZK'), ('MMK', 'MMK'), ('GEL', 'GEL'), ('GTQ', 'GTQ'), ('HUF', 'HUF'), ('TTD', 'TTD'), ('XOF', 'XOF'), ('BIF', 'BIF'), ('FKP', 'FKP'), ('TJS', 'TJS'), ('NAD', 'NAD'), ('LKR', 'LKR'), ('LSL', 'LSL'), ('CRC', 'CRC'), ('GNF', 'GNF'), ('KHR', 'KHR'), ('USDC', 'USDC'), ('SBD', 'SBD'), ('UZS', 'UZS'), ('SGD', 'SGD'), ('SEK', 'SEK'), ('WST', 'WST'), ('TWD', 'TWD'), ('VND', 'VND'), ('BBD', 'BBD'), ('ILS', 'ILS'), ('IDR', 'IDR'), ('AWG', 'AWG'), ('DKK', 'DKK'), ('ZAR', 'ZAR'), ('PHP', 'PHP'), ('SOS', 'SOS'), ('MGA', 'MGA'), ('UAH', 'UAH'), ('AOA', 'AOA'), ('BND', 'BND'), ('CNY', 'CNY'), ('VEF', 'VEF'), ('OMR', 'OMR'), ('PEN', 'PEN'), ('SAR', 'SAR'), ('PYG', 'PYG'), ('GBP', 'GBP'), ('NOK', 'NOK'), ('RON', 'RON'), ('KYD', 'KYD'), ('NIO', 'NIO'), ('TZS', 'TZS')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('used', 'used'), ('new', 'new')], default='new', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='prouduct_identifier_type',
            field=models.CharField(blank=True, choices=[('EAN', 'EAN'), ('UPC', 'UPC'), ('GCID', 'GCID'), ('ISBN', 'ISBN'), ('ASIN', 'ASIN')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('pounds', 'pounds'), ('Oz', 'Oz'), ('kilograms', 'kilograms')], max_length=255, null=True),
        ),
    ]
