# Generated by Django 4.0 on 2023-04-24 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_user_mobile_number_alter_coupon_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, choices=[('MRO', 'MRO'), ('RON', 'RON'), ('SCR', 'SCR'), ('OMR', 'OMR'), ('BTN', 'BTN'), ('PAB', 'PAB'), ('RUB', 'RUB'), ('UGX', 'UGX'), ('SAR', 'SAR'), ('XOF', 'XOF'), ('PYG', 'PYG'), ('YER', 'YER'), ('BIF', 'BIF'), ('UYU', 'UYU'), ('LVL', 'LVL'), ('MKD', 'MKD'), ('SLL', 'SLL'), ('BHD', 'BHD'), ('SZL', 'SZL'), ('GMD', 'GMD'), ('MUR', 'MUR'), ('TRY', 'TRY'), ('AZN', 'AZN'), ('TOP', 'TOP'), ('TND', 'TND'), ('BRL', 'BRL'), ('CAD', 'CAD'), ('RSD', 'RSD'), ('MGA', 'MGA'), ('HKD', 'HKD'), ('SHP', 'SHP'), ('TTD', 'TTD'), ('ARS', 'ARS'), ('ISK', 'ISK'), ('SVC', 'SVC'), ('MZN', 'MZN'), ('TZS', 'TZS'), ('AUD', 'AUD'), ('PHP', 'PHP'), ('GYD', 'GYD'), ('NOK', 'NOK'), ('MMK', 'MMK'), ('BYN', 'BYN'), ('KGS', 'KGS'), ('LSL', 'LSL'), ('BSD', 'BSD'), ('BMD', 'BMD'), ('CLP', 'CLP'), ('FJD', 'FJD'), ('EUR', 'EUR'), ('GEL', 'GEL'), ('CDF', 'CDF'), ('SOS', 'SOS'), ('MYR', 'MYR'), ('MXN', 'MXN'), ('BND', 'BND'), ('INR', 'INR'), ('MOP', 'MOP'), ('KHR', 'KHR'), ('HRK', 'HRK'), ('PEN', 'PEN'), ('BAM', 'BAM'), ('LAK', 'LAK'), ('ETB', 'ETB'), ('CZK', 'CZK'), ('AWG', 'AWG'), ('KRW', 'KRW'), ('WST', 'WST'), ('CHF', 'CHF'), ('ZMW', 'ZMW'), ('BWP', 'BWP'), ('KWD', 'KWD'), ('VEF', 'VEF'), ('KYD', 'KYD'), ('LTL', 'LTL'), ('BZD', 'BZD'), ('ILS', 'ILS'), ('NIO', 'NIO'), ('AMD', 'AMD'), ('AOA', 'AOA'), ('THB', 'THB'), ('CRC', 'CRC'), ('GIP', 'GIP'), ('TWD', 'TWD'), ('SGD', 'SGD'), ('SLE', 'SLE'), ('ALL', 'ALL'), ('GBP', 'GBP'), ('VND', 'VND'), ('XAF', 'XAF'), ('MWK', 'MWK'), ('RWF', 'RWF'), ('COP', 'COP'), ('STD', 'STD'), ('LBP', 'LBP'), ('PKR', 'PKR'), ('KES', 'KES'), ('BDT', 'BDT'), ('MDL', 'MDL'), ('MNT', 'MNT'), ('SBD', 'SBD'), ('QAR', 'QAR'), ('ANG', 'ANG'), ('PGK', 'PGK'), ('HNL', 'HNL'), ('AED', 'AED'), ('JPY', 'JPY'), ('FKP', 'FKP'), ('DZD', 'DZD'), ('MVR', 'MVR'), ('ZAR', 'ZAR'), ('UZS', 'UZS'), ('USD', 'USD'), ('SEK', 'SEK'), ('AFN', 'AFN'), ('MAD', 'MAD'), ('NZD', 'NZD'), ('GNF', 'GNF'), ('VUV', 'VUV'), ('XPF', 'XPF'), ('NGN', 'NGN'), ('NPR', 'NPR'), ('HTG', 'HTG'), ('CVE', 'CVE'), ('DJF', 'DJF'), ('JOD', 'JOD'), ('NAD', 'NAD'), ('BGN', 'BGN'), ('HUF', 'HUF'), ('JMD', 'JMD'), ('PLN', 'PLN'), ('LRD', 'LRD'), ('USDC', 'USDC'), ('CNY', 'CNY'), ('GTQ', 'GTQ'), ('SRD', 'SRD'), ('KMF', 'KMF'), ('DKK', 'DKK'), ('KZT', 'KZT'), ('DOP', 'DOP'), ('XCD', 'XCD'), ('EEK', 'EEK'), ('EGP', 'EGP'), ('BOB', 'BOB'), ('TJS', 'TJS'), ('IDR', 'IDR'), ('UAH', 'UAH'), ('LKR', 'LKR'), ('BBD', 'BBD'), ('GHS', 'GHS')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimension_type',
            field=models.CharField(blank=True, choices=[('centimeters', 'centimeters'), ('inches', 'inches')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prouduct_identifier_type',
            field=models.CharField(blank=True, choices=[('UPC', 'UPC'), ('GCID', 'GCID'), ('ISBN', 'ISBN'), ('ASIN', 'ASIN'), ('EAN', 'EAN')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('pounds', 'pounds'), ('kilograms', 'kilograms'), ('Oz', 'Oz')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('products', models.ManyToManyField(related_name='user_preferences', to='account.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'db_table': 'user_preference',
            },
        ),
    ]
