# Generated by Django 4.0 on 2023-04-25 10:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_alter_order_currency_alter_product_dimension_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_social_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, choices=[('DKK', 'DKK'), ('MWK', 'MWK'), ('NZD', 'NZD'), ('BRL', 'BRL'), ('MRO', 'MRO'), ('PGK', 'PGK'), ('CDF', 'CDF'), ('PHP', 'PHP'), ('BSD', 'BSD'), ('ETB', 'ETB'), ('SHP', 'SHP'), ('XOF', 'XOF'), ('JOD', 'JOD'), ('USDC', 'USDC'), ('COP', 'COP'), ('MMK', 'MMK'), ('MVR', 'MVR'), ('TTD', 'TTD'), ('FKP', 'FKP'), ('BDT', 'BDT'), ('RSD', 'RSD'), ('PYG', 'PYG'), ('EEK', 'EEK'), ('GYD', 'GYD'), ('KGS', 'KGS'), ('MUR', 'MUR'), ('OMR', 'OMR'), ('SLL', 'SLL'), ('BTN', 'BTN'), ('PKR', 'PKR'), ('DJF', 'DJF'), ('EUR', 'EUR'), ('SVC', 'SVC'), ('TWD', 'TWD'), ('NGN', 'NGN'), ('CNY', 'CNY'), ('TOP', 'TOP'), ('SEK', 'SEK'), ('BYN', 'BYN'), ('LSL', 'LSL'), ('BIF', 'BIF'), ('FJD', 'FJD'), ('DOP', 'DOP'), ('HRK', 'HRK'), ('SAR', 'SAR'), ('LVL', 'LVL'), ('ALL', 'ALL'), ('AUD', 'AUD'), ('BWP', 'BWP'), ('XCD', 'XCD'), ('UAH', 'UAH'), ('YER', 'YER'), ('AOA', 'AOA'), ('ISK', 'ISK'), ('NPR', 'NPR'), ('KMF', 'KMF'), ('KES', 'KES'), ('MDL', 'MDL'), ('BAM', 'BAM'), ('WST', 'WST'), ('ZMW', 'ZMW'), ('UYU', 'UYU'), ('MNT', 'MNT'), ('HTG', 'HTG'), ('CVE', 'CVE'), ('NIO', 'NIO'), ('GMD', 'GMD'), ('MOP', 'MOP'), ('VND', 'VND'), ('MZN', 'MZN'), ('SRD', 'SRD'), ('BBD', 'BBD'), ('UGX', 'UGX'), ('MKD', 'MKD'), ('UZS', 'UZS'), ('BMD', 'BMD'), ('LRD', 'LRD'), ('SOS', 'SOS'), ('CAD', 'CAD'), ('AZN', 'AZN'), ('CZK', 'CZK'), ('SLE', 'SLE'), ('SCR', 'SCR'), ('INR', 'INR'), ('MXN', 'MXN'), ('ANG', 'ANG'), ('NAD', 'NAD'), ('KRW', 'KRW'), ('LBP', 'LBP'), ('BGN', 'BGN'), ('NOK', 'NOK'), ('EGP', 'EGP'), ('CHF', 'CHF'), ('KYD', 'KYD'), ('KWD', 'KWD'), ('GIP', 'GIP'), ('USD', 'USD'), ('CLP', 'CLP'), ('SZL', 'SZL'), ('MGA', 'MGA'), ('IDR', 'IDR'), ('AMD', 'AMD'), ('THB', 'THB'), ('SBD', 'SBD'), ('TZS', 'TZS'), ('VEF', 'VEF'), ('CRC', 'CRC'), ('TRY', 'TRY'), ('BZD', 'BZD'), ('AED', 'AED'), ('STD', 'STD'), ('LKR', 'LKR'), ('XAF', 'XAF'), ('XPF', 'XPF'), ('GEL', 'GEL'), ('JMD', 'JMD'), ('PEN', 'PEN'), ('GTQ', 'GTQ'), ('MYR', 'MYR'), ('HUF', 'HUF'), ('GNF', 'GNF'), ('HKD', 'HKD'), ('RON', 'RON'), ('PAB', 'PAB'), ('AWG', 'AWG'), ('GHS', 'GHS'), ('BOB', 'BOB'), ('ARS', 'ARS'), ('QAR', 'QAR'), ('BND', 'BND'), ('PLN', 'PLN'), ('BHD', 'BHD'), ('MAD', 'MAD'), ('TJS', 'TJS'), ('ZAR', 'ZAR'), ('LAK', 'LAK'), ('ILS', 'ILS'), ('LTL', 'LTL'), ('TND', 'TND'), ('RWF', 'RWF'), ('JPY', 'JPY'), ('KZT', 'KZT'), ('SGD', 'SGD'), ('RUB', 'RUB'), ('GBP', 'GBP'), ('AFN', 'AFN'), ('VUV', 'VUV'), ('DZD', 'DZD'), ('HNL', 'HNL'), ('KHR', 'KHR')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('succeeded', 'succeeded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='prouduct_identifier_type',
            field=models.CharField(blank=True, choices=[('EAN', 'EAN'), ('UPC', 'UPC'), ('ASIN', 'ASIN'), ('GCID', 'GCID'), ('ISBN', 'ISBN')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('Oz', 'Oz'), ('pounds', 'pounds'), ('kilograms', 'kilograms')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('banner', models.ImageField(null=True, upload_to='offer_images')),
                ('discount_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_type', models.CharField(choices=[('currency', 'currency'), ('percentage', 'percentage')], max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_offers', to='account.user')),
                ('product', models.ManyToManyField(related_name='offer_products', to='account.Product')),
            ],
            options={
                'db_table': 'offer',
            },
        ),
    ]
